"use client";

import { AnimatePresence, motion, useMotionValue, useReducedMotion, useSpring, useTransform } from "framer-motion";
import { CalendarDays, Camera, Heart, MapPin, Play, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { JournalWorkspace } from "../../components/journal-workspace";
import { SiteFooter } from "../../components/site-footer";
import { SiteNav } from "../../components/site-nav";
import { useTheme } from "../theme-provider";

type Memory = { id: number; title: string; date: string; location: string; description: string; tag: "Trips" | "Daily Life" | "Milestones"; color: string; image: string; videoUrl?: string };
const memories: Memory[] = [
  { id: 1, title: "Sunset On The Pier", date: "May 12, 2025", location: "Manila Bay", description: "We chased golden light, forgot the time, and laughed over street food until midnight.", tag: "Trips", color: "memory-coral", image: "https://images.unsplash.com/photo-1507526883600-7a9a9c5a3b0c?auto=format&fit=crop&w=900&q=80", videoUrl: "https://www.youtube.com/embed/ScMzIvxBSi4" },
  { id: 2, title: "Rainy Day Cooking", date: "August 4, 2025", location: "Home Kitchen", description: "A power outage turned into candlelight cooking and our favorite comfort meal.", tag: "Daily Life", color: "memory-blush", image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=900&q=80" },
  { id: 3, title: "Anniversary Rooftop", date: "November 21, 2025", location: "City Center", description: "We wrote small promises for next year and watched the skyline flicker.", tag: "Milestones", color: "memory-rose", image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=80", videoUrl: "https://www.youtube.com/embed/LXb3EKWsInQ" },
  { id: 4, title: "Cafe Journal Day", date: "January 18, 2026", location: "Old Town Cafe", description: "An afternoon of journaling, sketching future goals, and collecting tiny moments.", tag: "Daily Life", color: "memory-lilac", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80" },
];
const filters = ["All", "Trips", "Daily Life", "Milestones"] as const;
type Filter = (typeof filters)[number];

function Scene() {
  const prefersReducedMotion = useReducedMotion();
  const pointerX = useMotionValue(50); const pointerY = useMotionValue(40);
  const smoothX = useSpring(pointerX, { stiffness: 70, damping: 22 }); const smoothY = useSpring(pointerY, { stiffness: 70, damping: 22 });
  const rotateX = useTransform(smoothY, [0, 100], [-8, 8]); const rotateY = useTransform(smoothX, [0, 100], [10, -10]);
  return <div className="journal-scene" onMouseMove={(event) => { if (!prefersReducedMotion) { pointerX.set((event.clientX / window.innerWidth) * 100); pointerY.set((event.clientY / window.innerHeight) * 100); } }}><motion.div className="journal-stage" style={prefersReducedMotion ? undefined : { rotateX, rotateY }}><div className="journal-plane" /><div className="journal-orb journal-orb-one" /><div className="journal-orb journal-orb-two" /><div className="journal-orb journal-orb-three" /><div className="journal-ring" /><Heart className="journal-floating-heart heart-one" fill="currentColor" size={28} /><Heart className="journal-floating-heart heart-two" fill="currentColor" size={20} /><Heart className="journal-floating-heart heart-three" fill="currentColor" size={36} /></motion.div><div className="journal-vignette" /></div>;
}

export default function UsersPage() {
  const { isNight } = useTheme();
  const prefersReducedMotion = useReducedMotion();
  const [activeFilter, setActiveFilter] = useState<Filter>("All");
  const [selectedMemory, setSelectedMemory] = useState<Memory | null>(null);
  const filteredMemories = activeFilter === "All" ? memories : memories.filter((memory) => memory.tag === activeFilter);
  return <main className={`journal-page ${isNight ? "is-night" : ""}`}><SiteNav variant="journal" /><Scene /><div className="journal-content"><section className="journal-hero"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="journal-glass-panel"><div className="journal-kicker"><Sparkles size={15} /> Our living love journal</div><h1 className="font-title text-5xl leading-tight text-pink-950 sm:text-7xl">A stylish memory space<br />for us, one moment at a time.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-pink-900/80 sm:text-lg">Your shared place for videos, tiny milestones, and everyday stories worth keeping close.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#memories" className="journal-primary"><Heart size={16} /> Explore memories</a><a href="#videos" className="journal-secondary"><Play size={16} /> Watch moments</a></div></motion.div></section>

<section id="memories" className="mt-12"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><h2 className="font-title text-4xl text-pink-950">Memory highlights</h2><div className="journal-filters">{filters.map((filter) => <button key={filter} type="button" onClick={() => setActiveFilter(filter)} className={activeFilter === filter ? "active" : ""}>{filter}</button>)}</div></div><div className="grid gap-5 sm:grid-cols-2">{filteredMemories.map((memory, index) => <motion.button type="button" key={memory.id} initial={prefersReducedMotion ? undefined : { opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: false, amount: .2 }} transition={prefersReducedMotion ? { duration: 0 } : { delay: index * 0.08, duration: .55, ease: "easeOut" }} onClick={() => setSelectedMemory(memory)} className="journal-memory-card"><div className={`memory-wash ${memory.color}`} /><div className="memory-image" style={{ backgroundImage: `url(${memory.image})` }} /><div className="relative text-left"><div className="mb-4 flex items-center justify-between text-pink-800"><span className="journal-tag">{memory.tag}</span><Camera size={16} /></div><h3 className="font-title text-3xl text-pink-950">{memory.title}</h3><p className="mt-3 text-sm leading-6 text-pink-900/80">{memory.description}</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-pink-800"><span className="journal-detail"><CalendarDays size={14} />{memory.date}</span><span className="journal-detail"><MapPin size={14} />{memory.location}</span></div><span className="journal-open">Open story <Sparkles size={14} /></span></div></motion.button>)}</div></section>

<section id="videos" className="mt-14 pb-16"><h2 className="font-title text-4xl text-pink-950">Video moments</h2><p className="mt-2 text-pink-900/75">The clips we will want to replay.</p><div className="mt-5 grid gap-4 md:grid-cols-3">{memories.filter((memory) => memory.videoUrl).map((memory) => <button type="button" key={memory.id} onClick={() => setSelectedMemory(memory)} className="journal-video-card"><div className={`video-thumb ${memory.color}`} style={{ backgroundImage: `linear-gradient(rgba(255,255,255,.2), rgba(255,179,212,.5)), url(${memory.image})` }}><Play size={24} fill="currentColor" /></div><div className="mt-4 flex items-center justify-between text-left"><h3 className="font-title text-2xl text-pink-950">{memory.title}</h3><span className="text-xs text-pink-800">{memory.date}</span></div></button>)}</div></section><JournalWorkspace /></div>

<AnimatePresence>{selectedMemory ? <motion.div className="journal-modal" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={(event) => { if (event.target === event.currentTarget) setSelectedMemory(null); }}><motion.div className="journal-modal-card" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 12 }}><div className={`modal-strip ${selectedMemory.color}`} /><div className="p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><h3 className="font-title text-3xl text-pink-950">{selectedMemory.title}</h3><button type="button" onClick={() => setSelectedMemory(null)} className="journal-close" aria-label="Close story"><X size={18} /></button></div><p className="mt-4 leading-7 text-pink-900/80">{selectedMemory.description}</p><div className="mt-5 flex flex-wrap gap-2"><span className="journal-tag">{selectedMemory.tag}</span><span className="journal-detail"><CalendarDays size={14} />{selectedMemory.date}</span></div>{selectedMemory.videoUrl ? <div className="mt-5 overflow-hidden rounded-xl"><iframe className="aspect-video w-full" src={selectedMemory.videoUrl} title={`${selectedMemory.title} video`} allowFullScreen /></div> : null}</div></motion.div></motion.div> : null}</AnimatePresence><SiteFooter homeHref="/users" /></main>;
}
