"use client";

import { CalendarDays, Camera, Check, Film, Heart, ImagePlus, Mic2, MoreHorizontal, Play, Sparkles, Upload, Video } from "lucide-react";
import { useState } from "react";

const calendarDays = [
  { day: 1, muted: true }, { day: 2, muted: true }, { day: 3, muted: true }, { day: 4, event: "Date night" }, { day: 5 }, { day: 6 }, { day: 7 },
  { day: 8 }, { day: 9 }, { day: 10 }, { day: 11 }, { day: 12, event: "Pier sunset" }, { day: 13 }, { day: 14, event: "Our day" },
  { day: 15 }, { day: 16 }, { day: 17 }, { day: 18 }, { day: 19 }, { day: 20 }, { day: 21 },
  { day: 22 }, { day: 23 }, { day: 24 }, { day: 25, event: "Dinner" }, { day: 26 }, { day: 27 }, { day: 28 },
  { day: 29 }, { day: 30 }, { day: 31 },
];

const compilationFrames = [
  "https://images.unsplash.com/photo-1507526883600-7a9a9c5a3b0c?auto=format&fit=crop&w=400&q=75",
  "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=400&q=75",
  "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=400&q=75",
];

function SectionHeading({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon: typeof CalendarDays }) {
  return <div className="workspace-heading"><div className="workspace-heading-icon"><Icon size={19} /></div><div><p className="workspace-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div></div>;
}

export function JournalWorkspace() {
  const [mood, setMood] = useState("Soft");
  return <div className="journal-workspace">
    <section id="capture" className="workspace-section"><SectionHeading eyebrow="Keep the moment" title="Capture together" description="Bring in the photos and clips that make today worth remembering." icon={ImagePlus} /><div className="capture-grid"><label className="upload-dropzone"><input type="file" accept="image/*,video/*" multiple /><Upload size={24} /><strong>Drop photos or videos here</strong><span>or choose from your device</span><small>JPG, PNG, MP4 up to 50 MB</small></label><div className="capture-side"><button type="button" className="capture-action"><Camera size={18} /><span><strong>Take a photo</strong><small>Save a little piece of right now</small></span><MoreHorizontal size={17} /></button><button type="button" className="capture-action"><Video size={18} /><span><strong>Record a moment</strong><small>Make a clip for your future selves</small></span><MoreHorizontal size={17} /></button><div className="capture-note"><Sparkles size={16} /><span>AI sorting will be available when the journal is connected.</span></div></div></div></section>

    <section id="studio" className="workspace-section"><SectionHeading eyebrow="Make something from it" title="Compilation studio" description="Turn a handful of moments into a story you can replay." icon={Film} /><div className="studio-grid"><div className="compilation-preview"><div className="compilation-collage">{compilationFrames.map((frame) => <div key={frame} style={{ backgroundImage: `url(${frame})` }} />)}<div className="compilation-play"><Play size={18} fill="currentColor" /></div></div><div className="compilation-meta"><div><span className="workspace-eyebrow">Draft compilation</span><h3>August, in little pieces</h3><p>12 moments · 02:48 total</p></div><button type="button" className="workspace-primary"><Play size={15} /> Preview</button></div></div><div className="studio-options"><label>Compilation mood<select defaultValue="warm"><option value="warm">Warm and nostalgic</option><option value="bright">Bright and playful</option><option value="quiet">Quiet and cinematic</option></select></label><label>Story title<input type="text" defaultValue="August, in little pieces" /></label><button type="button" className="workspace-primary"><Sparkles size={15} /> Create a mock compilation</button><p className="workspace-hint">This preview shows the future workflow. Video generation will be connected later.</p></div></div></section>

    <section id="calendar" className="workspace-section"><SectionHeading eyebrow="Make time for us" title="Shared calendar" description="A simple place for plans, dates, and the days you are already looking forward to." icon={CalendarDays} /><div className="calendar-layout"><div className="calendar-card"><div className="calendar-top"><button type="button" aria-label="Previous month">&#8592;</button><h3>September 2026</h3><button type="button" aria-label="Next month">&#8594;</button></div><div className="calendar-weekdays">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarDays.map(({ day, muted, event }) => <button key={day} type="button" className={`${muted ? "muted" : ""} ${event ? "has-event" : ""}`} title={event}>{day}{event ? <i /> : null}</button>)}</div></div><div className="upcoming-card"><span className="workspace-eyebrow">Coming up</span><div className="upcoming-event"><div className="date-block"><strong>14</strong><span>SEP</span></div><div><h3>Our day</h3><p>Anniversary dinner · 7:30 PM</p><span><Heart size={13} fill="currentColor" /> Both of us</span></div></div><div className="upcoming-event"><div className="date-block"><strong>25</strong><span>SEP</span></div><div><h3>Dinner at home</h3><p>Try the new pasta recipe</p><span><Heart size={13} fill="currentColor" /> Both of us</span></div></div><button type="button" className="workspace-secondary"><CalendarDays size={15} /> Add a shared plan</button></div></div></section>

    <section id="weekly" className="workspace-section"><SectionHeading eyebrow="A little ritual" title="Weekly compilation" description="A gentle recap waiting for you at the end of the week." icon={Sparkles} /><div className="weekly-card"><div className="weekly-art"><div className="weekly-orbit" /><Heart size={32} fill="currentColor" /><span>WEEK 36</span></div><div className="weekly-copy"><span className="workspace-eyebrow">Ready this Sunday</span><h3>Your week, held close.</h3><p>We found 8 photos, 2 videos, and 4 notes from the moments you shared this week.</p><div className="weekly-stats"><span><strong>8</strong> photos</span><span><strong>2</strong> videos</span><span><strong>4</strong> notes</span></div><button type="button" className="workspace-primary"><Play size={15} /> Preview weekly story</button></div></div></section>

    <section id="diary" className="workspace-section diary-section"><SectionHeading eyebrow="Put it somewhere safe" title="Private diary" description="A place for the full truth of the day: the frustrations, the happiness, and everything between." icon={Heart} /><div className="diary-layout"><div className="diary-editor"><div className="diary-toolbar"><span>Today, September 13</span><div><button type="button" aria-label="Add photo"><ImagePlus size={16} /></button><button type="button" aria-label="Record voice note"><Mic2 size={16} /></button></div></div><textarea placeholder="What is on your heart today?" /><div className="diary-footer"><div className="mood-picker"><span>Today feels</span>{["Soft", "Bright", "Heavy", "Hopeful"].map((item) => <button key={item} type="button" className={mood === item ? "active" : ""} onClick={() => setMood(item)}>{item}</button>)}</div><button type="button" className="workspace-primary"><Check size={15} /> Save entry</button></div></div><aside className="diary-prompt"><Sparkles size={18} /><span className="workspace-eyebrow">A thought to carry</span><p>“You do not have to make a moment perfect for it to be worth keeping.”</p><small>Your diary is private by default.</small></aside></div></section>
  </div>;
}
